src/java/jpa/entities/DodavatelLogin.java
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

package jpa.entities;

import java.io.Serializable;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.OneToOne;
import javax.persistence.Table;

/**
 *
 * @author Frapko
 */
@Entity
@Table(name = "dodavatel_login")
@NamedQueries({
    @NamedQuery(name = "DodavatelLogin.findAll", query = "SELECT d FROM DodavatelLogin d"),
    @NamedQuery(name = "DodavatelLogin.findById", query = "SELECT d FROM DodavatelLogin d WHERE d.id = :id"),
    @NamedQuery(name = "DodavatelLogin.findByLogin", query = "SELECT d FROM DodavatelLogin d WHERE d.login = :login"),
    @NamedQuery(name = "DodavatelLogin.findByHeslo", query = "SELECT d FROM DodavatelLogin d WHERE d.heslo = :heslo")})
public class DodavatelLogin implements Serializable {
    private static final long serialVersionUID = 1L;
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Basic(optional = false)
    @Column(name = "id")
    private Integer id;
    @Basic(optional = false)
    @Column(name = "login")
    private String login;
    @Basic(optional = false)
    @Column(name = "heslo")
    private String heslo;
    @JoinColumn(name = "id", referencedColumnName = "id", insertable = false, updatable = false)
    @OneToOne(optional = false)
    private Dodavatel dodavatel;

    public DodavatelLogin() {
    }

    public DodavatelLogin(Integer id) {
        this.id = id;
    }

    public DodavatelLogin(Integer id, String login, String heslo) {
        this.id = id;
        this.login = login;
        this.heslo = heslo;
    }

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getLogin() {
        return login;
    }

    public void setLogin(String login) {
        this.login = login;
    }

    public String getHeslo() {
        return heslo;
    }

    public void setHeslo(String heslo) {
        this.heslo = heslo;
    }

    public Dodavatel getDodavatel() {
        return dodavatel;
    }

    public void setDodavatel(Dodavatel dodavatel) {
        this.dodavatel = dodavatel;
    }

    @Override
    public int hashCode() {
        int hash = 0;
        hash += (id != null ? id.hashCode() : 0);
        return hash;
    }

    @Override
    public boolean equals(Object object) {
        // TODO: Warning - this method won't work in the case the id fields are not set
        if (!(object instanceof DodavatelLogin)) {
            return false;
        }
        DodavatelLogin other = (DodavatelLogin) object;
        if ((this.id == null && other.id != null) || (this.id != null && !this.id.equals(other.id))) {
            return false;
        }
        return true;
    }

    @Override
    public String toString() {
        return "jpa.entities.DodavatelLogin[id=" + id + "]";
    }

}

src/java/jsf/DodavatelLoginController.java
package jsf;

import jpa.entities.DodavatelLogin;
import jsf.util.JsfUtil;
import jsf.util.PaginationHelper;
import jpa.session.DodavatelLoginFacade;

import java.util.ResourceBundle;
import javax.ejb.EJB;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;
import javax.faces.component.UIComponent;
import javax.faces.context.FacesContext;
import javax.faces.convert.Converter;
import javax.faces.convert.FacesConverter;
import javax.faces.model.DataModel;
import javax.faces.model.ListDataModel;
import javax.faces.model.SelectItem;

@ManagedBean (name="dodavatelLoginController")
@SessionScoped
public class DodavatelLoginController {

    private DodavatelLogin current;
    private DataModel items = null;
    @EJB private jpa.session.DodavatelLoginFacade ejbFacade;
    private PaginationHelper pagination;
    private int selectedItemIndex;

    public DodavatelLoginController() {
    }

    public DodavatelLogin getSelected() {
        if (current == null) {
            current = new DodavatelLogin();
            selectedItemIndex = -1;
        }
        return current;
    }

    private DodavatelLoginFacade getFacade() {
        return ejbFacade;
    }

    public PaginationHelper getPagination() {
        if (pagination == null) {
            pagination = new PaginationHelper(10) {

                @Override
                public int getItemsCount() {
                    return getFacade().count();
                }

                @Override
                public DataModel createPageDataModel() {
                    return new ListDataModel(getFacade().findRange(new int[]{getPageFirstItem(), getPageFirstItem()+getPageSize()}));
                }
            };
        }
        return pagination;
    }

    public String prepareList() {
        recreateModel();
        return "List";
    }

    public String prepareView() {
        current = (DodavatelLogin)getItems().getRowData();
        selectedItemIndex = pagination.getPageFirstItem() + getItems().getRowIndex();
        return "View";
    }

    public String prepareCreate() {
        current = new DodavatelLogin();
        selectedItemIndex = -1;
        return "Create";
    }

    public String create() {
        try {
            getFacade().create(current);
            JsfUtil.addSuccessMessage(ResourceBundle.getBundle("/resources/Bundle").getString("DodavatelLoginCreated"));
            return prepareCreate();
        } catch (Exception e) {
            JsfUtil.addErrorMessage(e, ResourceBundle.getBundle("/resources/Bundle").getString("PersistenceErrorOccured"));
            return null;
        }
    }

    public String prepareEdit() {
        current = (DodavatelLogin)getItems().getRowData();
        selectedItemIndex = pagination.getPageFirstItem() + getItems().getRowIndex();
        return "Edit";
    }

    public String update() {
        try {
            getFacade().edit(current);
            JsfUtil.addSuccessMessage(ResourceBundle.getBundle("/resources/Bundle").getString("DodavatelLoginUpdated"));
            return "View";
        } catch (Exception e) {
            JsfUtil.addErrorMessage(e, ResourceBundle.getBundle("/resources/Bundle").getString("PersistenceErrorOccured"));
            return null;
        }
    }

    public String destroy() {
        current = (DodavatelLogin)getItems().getRowData();
        selectedItemIndex = pagination.getPageFirstItem() + getItems().getRowIndex();
        performDestroy();
        recreateModel();
        return "List";
    }

    public String destroyAndView() {
        performDestroy();
        recreateModel();
        updateCurrentItem();
        if (selectedItemIndex >= 0) {
            return "View";
        } else {
            // all items were removed - go back to list
            recreateModel();
            return "List";
        }
    }

    private void performDestroy() {
        try {
            getFacade().remove(current);
            JsfUtil.addSuccessMessage(ResourceBundle.getBundle("/resources/Bundle").getString("DodavatelLoginDeleted"));
        } catch (Exception e) {
            JsfUtil.addErrorMessage(e, ResourceBundle.getBundle("/resources/Bundle").getString("PersistenceErrorOccured"));
        }
    }

    private void updateCurrentItem() {
        int count = getFacade().count();
        if (selectedItemIndex >= count) {
            // selected index cannot be bigger than number of items:
            selectedItemIndex = count-1;
            // go to previous page if last page disappeared:
            if (pagination.getPageFirstItem() >= count) {
                pagination.previousPage();
            }
        }
        if (selectedItemIndex >= 0) {
            current = getFacade().findRange(new int[]{selectedItemIndex, selectedItemIndex+1}).get(0);
        }
    }

    public DataModel getItems() {
        if (items == null) {
            items = getPagination().createPageDataModel();
        }
        return items;
    }

    private void recreateModel() {
        items = null;
    }

    public String next() {
        getPagination().nextPage();
        recreateModel();
        return "List";
    }

    public String previous() {
        getPagination().previousPage();
        recreateModel();
        return "List";
    }

    public SelectItem[] getItemsAvailableSelectMany() {
        return JsfUtil.getSelectItems(ejbFacade.findAll(), false);
    }

    public SelectItem[] getItemsAvailableSelectOne() {
        return JsfUtil.getSelectItems(ejbFacade.findAll(), true);
    }

    @FacesConverter(forClass=DodavatelLogin.class)
    public static class DodavatelLoginControllerConverter implements Converter {

        public Object getAsObject(FacesContext facesContext, UIComponent component, String value) {
            if (value == null || value.length() == 0) {
                return null;
            }
            DodavatelLoginController controller = (DodavatelLoginController)facesContext.getApplication().getELResolver().
                    getValue(facesContext.getELContext(), null, "dodavatelLoginController");
            return controller.ejbFacade.find(getKey(value));
        }

        java.lang.Integer getKey(String value) {
            java.lang.Integer key;
            key = Integer.valueOf(value);
            return key;
        }

        String getStringKey(java.lang.Integer value) {
            StringBuffer sb = new StringBuffer();
            sb.append(value);
            return sb.toString();
        }

        public String getAsString(FacesContext facesContext, UIComponent component, Object object) {
            if (object == null) {
                return null;
            }
            if (object instanceof DodavatelLogin) {
                DodavatelLogin o = (DodavatelLogin) object;
                return getStringKey(o.getId());
            } else {
                throw new IllegalArgumentException("object " + object + " is of type " + object.getClass().getName() + "; expected type: "+DodavatelLoginController.class.getName());
            }
        }

    }

}

web/dodavatelLogin/Create.xhtml
<?xml version="1.0" encoding="ISO-8859-1" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core">

    <ui:composition template="/template.xhtml">
        <ui:define name="title">
            <h:outputText value="#{bundle.CreateDodavatelLoginTitle}"></h:outputText>
        </ui:define>
        <ui:define name="body">
            <h:panelGroup id="messagePanel" layout="block">
                <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
            </h:panelGroup>
            <h:form>
                <h:panelGrid columns="2">
                    <h:outputLabel value="#{bundle.CreateDodavatelLoginLabel_id}" for="id" />
                    <h:inputText id="id" value="#{dodavatelLoginController.selected.id}" title="#{bundle.CreateDodavatelLoginTitle_id}" required="true" requiredMessage="#{bundle.CreateDodavatelLoginRequiredMessage_id}"/>
                    <h:outputLabel value="#{bundle.CreateDodavatelLoginLabel_login}" for="login" />
                    <h:inputText id="login" value="#{dodavatelLoginController.selected.login}" title="#{bundle.CreateDodavatelLoginTitle_login}" required="true" requiredMessage="#{bundle.CreateDodavatelLoginRequiredMessage_login}"/>
                    <h:outputLabel value="#{bundle.CreateDodavatelLoginLabel_heslo}" for="heslo" />
                    <h:inputText id="heslo" value="#{dodavatelLoginController.selected.heslo}" title="#{bundle.CreateDodavatelLoginTitle_heslo}" required="true" requiredMessage="#{bundle.CreateDodavatelLoginRequiredMessage_heslo}"/>
                    <h:outputLabel value="#{bundle.CreateDodavatelLoginLabel_dodavatel}" for="dodavatel" />
                    <h:selectOneMenu id="dodavatel" value="#{dodavatelLoginController.selected.dodavatel}" title="#{bundle.CreateDodavatelLoginTitle_dodavatel}" required="true" requiredMessage="#{bundle.CreateDodavatelLoginRequiredMessage_dodavatel}">
                        <f:selectItems value="#{dodavatelController.itemsAvailableSelectOne}"/>
                    </h:selectOneMenu>
                </h:panelGrid>
                <br />
                <h:commandLink action="#{dodavatelLoginController.create}" value="#{bundle.CreateDodavatelLoginSaveLink}" />
                <br />
                <br />
                <h:commandLink action="#{dodavatelLoginController.prepareList}" value="#{bundle.CreateDodavatelLoginShowAllLink}" immediate="true"/>
                <br />
                <br />
                <h:commandLink value="#{bundle.CreateDodavatelLoginIndexLink}" action="/index" immediate="true" />
            </h:form>
        </ui:define>
    </ui:composition>

</html>

web/dodavatelLogin/Edit.xhtml
<?xml version="1.0" encoding="ISO-8859-1" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core">

    <ui:composition template="/template.xhtml">
        <ui:define name="title">
            <h:outputText value="#{bundle.EditDodavatelLoginTitle}"></h:outputText>
        </ui:define>
        <ui:define name="body">
            <h:panelGroup id="messagePanel" layout="block">
                <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
            </h:panelGroup>
            <h:form>
                <h:panelGrid columns="2">
                    <h:outputLabel value="#{bundle.EditDodavatelLoginLabel_id}" for="id" />
                    <h:inputText id="id" value="#{dodavatelLoginController.selected.id}" title="#{bundle.EditDodavatelLoginTitle_id}" required="true" requiredMessage="#{bundle.EditDodavatelLoginRequiredMessage_id}"/>
                    <h:outputLabel value="#{bundle.EditDodavatelLoginLabel_login}" for="login" />
                    <h:inputText id="login" value="#{dodavatelLoginController.selected.login}" title="#{bundle.EditDodavatelLoginTitle_login}" required="true" requiredMessage="#{bundle.EditDodavatelLoginRequiredMessage_login}"/>
                    <h:outputLabel value="#{bundle.EditDodavatelLoginLabel_heslo}" for="heslo" />
                    <h:inputText id="heslo" value="#{dodavatelLoginController.selected.heslo}" title="#{bundle.EditDodavatelLoginTitle_heslo}" required="true" requiredMessage="#{bundle.EditDodavatelLoginRequiredMessage_heslo}"/>
                    <h:outputLabel value="#{bundle.EditDodavatelLoginLabel_dodavatel}" for="dodavatel" />
                    <h:selectOneMenu id="dodavatel" value="#{dodavatelLoginController.selected.dodavatel}" title="#{bundle.EditDodavatelLoginTitle_dodavatel}" required="true" requiredMessage="#{bundle.EditDodavatelLoginRequiredMessage_dodavatel}">
                        <f:selectItems value="#{dodavatelController.itemsAvailableSelectOne}"/>
                    </h:selectOneMenu>
                </h:panelGrid>
                <h:commandLink action="#{dodavatelLoginController.update}" value="#{bundle.EditDodavatelLoginSaveLink}"/>
                <br />
                <br />
                <h:commandLink action="View" value="#{bundle.EditDodavatelLoginViewLink}" immediate="true"/>
                <br />
                <h:commandLink action="#{dodavatelLoginController.prepareList}" value="#{bundle.EditDodavatelLoginShowAllLink}" immediate="true"/>
                <br />
                <br />
                <h:commandLink value="#{bundle.EditDodavatelLoginIndexLink}" action="/index" immediate="true" />
            </h:form>
        </ui:define>
    </ui:composition>

</html>

web/dodavatelLogin/List.xhtml
<?xml version="1.0" encoding="ISO-8859-1" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core">

    <ui:composition template="/template.xhtml">
        <ui:define name="title">
            <h:outputText value="#{bundle.ListDodavatelLoginTitle}"></h:outputText>
        </ui:define>
        <ui:define name="body">
        <h:form styleClass="jsfcrud_list_form">
            <h:panelGroup id="messagePanel" layout="block">
                <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
            </h:panelGroup>
            <h:outputText escape="false" value="#{bundle.ListDodavatelLoginEmpty}" rendered="#{dodavatelLoginController.items.rowCount == 0}"/>
            <h:panelGroup rendered="#{dodavatelLoginController.items.rowCount > 0}">
                <h:outputText value="#{dodavatelLoginController.pagination.pageFirstItem + 1}..#{dodavatelLoginController.pagination.pageLastItem + 1}/#{dodavatelLoginController.pagination.itemsCount}"/>&nbsp;
                <h:commandLink action="#{dodavatelLoginController.previous}" value="#{bundle.Previous} #{dodavatelLoginController.pagination.pageSize}" rendered="#{dodavatelLoginController.pagination.hasPreviousPage}"/>&nbsp;
                <h:commandLink action="#{dodavatelLoginController.next}" value="#{bundle.Next} #{dodavatelLoginController.pagination.pageSize}" rendered="#{dodavatelLoginController.pagination.hasNextPage}"/>&nbsp;
                <h:dataTable value="#{dodavatelLoginController.items}" var="item" border="0" cellpadding="2" cellspacing="0" rowClasses="jsfcrud_odd_row,jsfcrud_even_row" rules="all" style="border:solid 1px">
                    <h:column>
                        <f:facet name="header">
                            <h:outputText value="#{bundle.ListDodavatelLoginTitle_id}"/>
                        </f:facet>
                        <h:outputText value="#{item.id}"/>
                    </h:column>
                    <h:column>
                        <f:facet name="header">
                            <h:outputText value="#{bundle.ListDodavatelLoginTitle_login}"/>
                        </f:facet>
                        <h:outputText value="#{item.login}"/>
                    </h:column>
                    <h:column>
                        <f:facet name="header">
                            <h:outputText value="#{bundle.ListDodavatelLoginTitle_heslo}"/>
                        </f:facet>
                        <h:outputText value="#{item.heslo}"/>
                    </h:column>
                    <h:column>
                        <f:facet name="header">
                            <h:outputText value="#{bundle.ListDodavatelLoginTitle_dodavatel}"/>
                        </f:facet>
                        <h:outputText value="#{item.dodavatel}"/>
                    </h:column>
                    <h:column>
                        <f:facet name="header">
                            <h:outputText value="&nbsp;"/>
                        </f:facet>
                        <h:commandLink action="#{dodavatelLoginController.prepareView}" value="#{bundle.ListDodavatelLoginViewLink}"/>
                        <h:outputText value=" "/>
                        <h:commandLink action="#{dodavatelLoginController.prepareEdit}" value="#{bundle.ListDodavatelLoginEditLink}"/>
                        <h:outputText value=" "/>
                        <h:commandLink action="#{dodavatelLoginController.destroy}" value="#{bundle.ListDodavatelLoginDestroyLink}"/>
                    </h:column>
                </h:dataTable>
            </h:panelGroup>
            <br />
            <h:commandLink action="#{dodavatelLoginController.prepareCreate}" value="#{bundle.ListDodavatelLoginCreateLink}"/>
            <br />
            <br />
            <h:commandLink value="#{bundle.ListDodavatelLoginIndexLink}" action="/index" immediate="true" />
        </h:form>
        </ui:define>
    </ui:composition>

</html>

web/dodavatelLogin/View.xhtml
<?xml version="1.0" encoding="ISO-8859-1" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core">

    <ui:composition template="/template.xhtml">
        <ui:define name="title">
            <h:outputText value="#{bundle.ViewDodavatelLoginTitle}"></h:outputText>
        </ui:define>
        <ui:define name="body">
            <h:panelGroup id="messagePanel" layout="block">
                <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
            </h:panelGroup>
            <h:form>
                <h:panelGrid columns="2">
                    <h:outputText value="#{bundle.ViewDodavatelLoginLabel_id}"/>
                    <h:outputText value="#{dodavatelLoginController.selected.id}" title="#{bundle.ViewDodavatelLoginTitle_id}"/>
                    <h:outputText value="#{bundle.ViewDodavatelLoginLabel_login}"/>
                    <h:outputText value="#{dodavatelLoginController.selected.login}" title="#{bundle.ViewDodavatelLoginTitle_login}"/>
                    <h:outputText value="#{bundle.ViewDodavatelLoginLabel_heslo}"/>
                    <h:outputText value="#{dodavatelLoginController.selected.heslo}" title="#{bundle.ViewDodavatelLoginTitle_heslo}"/>
                    <h:outputText value="#{bundle.ViewDodavatelLoginLabel_dodavatel}"/>
                    <h:outputText value="#{dodavatelLoginController.selected.dodavatel}" title="#{bundle.ViewDodavatelLoginTitle_dodavatel}"/>
                </h:panelGrid>
                <br />
                <h:commandLink action="#{dodavatelLoginController.destroyAndView}" value="#{bundle.ViewDodavatelLoginDestroyLink}"/>
                <br />
                <br />
                <h:commandLink action="Edit" value="#{bundle.ViewDodavatelLoginEditLink}"/>
                <br />
                <h:commandLink action="#{dodavatelLoginController.prepareCreate}" value="#{bundle.ViewDodavatelLoginCreateLink}" />
                <br />
                <h:commandLink action="#{dodavatelLoginController.prepareList}" value="#{bundle.ViewDodavatelLoginShowAllLink}"/>
                <br />
                <br />
                <h:commandLink value="#{bundle.ViewDodavatelLoginIndexLink}" action="/index" immediate="true" />

            </h:form>
        </ui:define>
    </ui:composition>

</html>